# Generated by Django 5.1.1 on 2026-10-03 17:48

import common.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Código uuid4')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Colaborador')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('access_level', models.CharField(choices=[('ADM', 'Administração'), ('USR', 'Usuário')], default='DEV', max_length=3, verbose_name='Nível de Acesso')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', common.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Código uuid4')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Colaborador')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('access_level', models.CharField(choices=[('ADM', 'Administração'), ('USR', 'Usuário')], default='DEV', max_length=3, verbose_name='Nível de Acesso')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical custom user',
                'verbose_name_plural': 'historical custom users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash do Token')),
                ('expires_at', models.DateTimeField(verbose_name='Data de Expiração')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Uso')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Invalidação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_recoveries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recuperação de Senha',
                'verbose_name_plural': 'Recuperações de Senha',
                'indexes': [models.Index(fields=['token_hash'], name='user_passwo_token_h_49e6d8_idx'), models.Index(fields=['user', 'created_at'], name='user_passwo_user_id_a4a576_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('invalidated_at__isnull', True), ('used_at__isnull', True)), fields=('user',), name='unique_active_password_recovery_per_user')],
            },
        ),
    ]
