# Generated by Django 5.1.1 on 2026-05-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_level',
            field=models.CharField(choices=[('ADM', 'Administração'), ('USR', 'Usuário')], default='DEV', max_length=3, verbose_name='Nível de Acesso'),
        ),
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash do Token')),
                ('expires_at', models.DateTimeField(verbose_name='Data de Expiração')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Uso')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Invalidação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_recoveries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recuperação de Senha',
                'verbose_name_plural': 'Recuperações de Senha',
                'indexes': [models.Index(fields=['token_hash'], name='user_passwo_token_h_49e6d8_idx'), models.Index(fields=['user', 'created_at'], name='user_passwo_user_id_a4a576_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('invalidated_at__isnull', True), ('used_at__isnull', True)), fields=('user',), name='unique_active_password_recovery_per_user')],
            },
        ),
    ]
